### PR TITLE
cli causemosify-multi write dfs to tmp parquet files #54

### PR DESCRIPTION
**Pull request by GoogleSheets**
### Description

- address #54 
-  does not address netCDFs specifically, but modifies `cli.py` `causemosify-multi()` to write dataframes to parquet files while looping
- parquets require the extra step of separating str type columns, but csv read/write results in wrong dtypes.
- passed unit testing

### Todo

- benchmarking?

### CODE REVIEW

**Comment by brandomr** [comment]
Note to self--test with https://jataware-world-modelers.s3.amazonaws.com/dev/topoflow-run.zip

**Comment by GoogleSheets** [comment]
### Status Update

- uses code copied from `mixmasta.process()` to load `netcdf` into `df`
- chunks `df` and writes to `pkl` files
- iterates to read each `pkl` file, calls `mixmasta.normalize()`, and writes to a new `pkl` file
- After looping, reassembles all the processed `pkl` files into a `df` and writes this to parquet files.

### Notes before building
`cli.py` is edited to run in VS Code directly
- `download` and `mixmasta` imports are modified; revert to commented out imports before building
- uncomment `@cli` and `@click` decorations before `def causemosify_multi()`
- at bottom uncomment `cli()` and comment out test code.


### Timings
- I/O with pickle files is very fast
- using lpjml-sample.nc and edited mapper file: [lpml_mapper.json.txt](https://github.com/jataware/mixmasta/files/7188261/lpml_mapper.json.txt)
  - loads and writes tmp pickle files in ~8 seconds
  - normalization loop takes ~35 minutes
  - reassembly of dataframe from pickle files takes ~12 seconds (41,932,800 rows, 11 cols) df is 11.5 GB memory in python
  - container memory peaks at 18GB during reassembly and writing parquet files

This will probably break if multiple files of this size are reloaded into a single dataframe.

Wrapped up quickly; may review later in case I missed something.

**Comment by GoogleSheets** [comment]
### Description
Final commits:
- `cli.py` `causemosify` and `causemosify-multi` use `chunk normalize()` where the input file is read and chunked to `pkl` files. These are then read in chunks of 100,000 lines and pushed to `mixmasta.normalize()`. Each cycle the resulting dataframe is saved to a temp `pkl` file.
- After an input file is processed, the tmp `pkl` files are reassembled into a pandas dataframe and written to parquet files.
- A df_geocode dataframe is maintained and passed through to `mixmasta.geocode()` to cache geocoded lat/long values. `geocode()` is further refactored to drop duplicate lat/long values.
- GADM is cached in `cli.py causemosify` methods.
- Address #57 in `mixmasta.normalize()`.
- modified `test_mixmasta.py` to handle multi-parquet out files in the test.

**Comment by brandomr** [comment]
Looks great, tests pass, and lpjml sample processes quickly!

**Review by brandomr — APPROVED** [review]

**Pull request merged**
