### PR TITLE
Feature/rtk multiband geotiff

### PR DESCRIPTION
**Pull request by GoogleSheets**

### CODE REVIEW

**Comment by GoogleSheets** [comment]
### What's New

- Added multi-band tiff support
- Modified `meta` section of JSON schema expected from **SpaceTag** (see #28 )
- Optimized dataframe memory size before and after normalize().
- Added support for `geo=admin0` and `geo=admin1`

### Rationale

#### Multi-band tiff
Links to #28   , briefly: Support multi-band geotiff where each band will represent either a different time, a different feature, or a qualifier on the feature.

#### admin0 / admin1
Some models may have spatial resolution that resolves to very large areas ie. a country. In these instances, geocoding to admin1 or admin2 may be misleading. Enable the use to pass `geo=admin0` (country) or `geo=admin1` (state/territory) so that geocoding does not return values for higher resolution admins (e.g. admin2, admin3).

> This implementation requires that **SpaceTag** specify the `geo` value when calling `causemosify()` or `process()`.



### Details

#### Schema change
Added the following to the `meta` section:
```
- "band_name": str
- "bands": dict(str, object)
```
```
"meta":
    {
        "ftype": "geotiff",
        "date": "12/29/2004",
        "feature_name": "asset wealth",		
        "band": 0,
        "null_val": 0,	
        "band_name": "year",
        "bands":{
	        "1": 2018,
	        "2": 2019,
	        "3": 2020,
	        "4": 2021		
        }
    }
```

#### Optimization:  dataframe dtype optimization and reindexing

november_tests_atlasai_assetwealth_allyears_2km.tif
```
Without n = 5 mean: 126.1 sec stdev: 2.096
With    n = 5 mean:  41.9 sec stdev: 0.873
```

### Testing the PR
>Remove .txt extension from filenames.

4 bands representing years of asset data (~40 seconds to run):
[november_tests_atlasai_assetwealth_allyears_2km.json.txt](https://github.com/jataware/mixmasta/files/6832747/november_tests_atlasai_assetwealth_allyears_2km.json.txt)
[november_tests_atlasai_assetwealth_allyears_2km.tif.txt](https://github.com/jataware/mixmasta/files/6832748/november_tests_atlasai_assetwealth_allyears_2km.tif.txt)

220 bands representing months of flood data (~212 seconds to run):
[flood_monthly.json.txt](https://github.com/jataware/mixmasta/files/6832761/flood_monthly.json.txt)
[flood_monthly.tif.txt](https://github.com/jataware/mixmasta/files/6832762/flood_monthly.tif.txt)

**Comment by brandomr** [comment]
@GoogleSheets what happens if the band keys are `integer` not `string`? That would make more sense to me so that band 1 is just `1: "bandvalue"` instead of `"1": "bandvalue"`.

With the flood file, I am guessing this is really monthly data so I think in a "real-world" situation you'd have the `band_name` be something like `"month_of_year"` and the values something like:

```
"1":"01/2000"
"2":"02/2000",
"3":"03/2000",
...
"13":"01/2001",
``` 

with an appropriate time formatter.

**Comment by brandomr** [comment]
@GoogleSheets could you add the schema that you have as a PR on spacetag into this branch then we'll merge it?

**Comment by GoogleSheets** [comment]
@brandomr The updated **spacetag** schema is added but the validation is still off. I'll also be adding the parquet / pyarrow fix to this PR.

**Comment by GoogleSheets** [comment]
## Updates

### SpaceTag

 `mixmasta/spacetag_schema.py` was updated to match **SpaceTag** project schema, but **mixmasta** does not yet validate this.

### Rainfall Error

#### Description

- Brad reported a pyarrow exception when writing the parquet files.
- Column **MainCause** qualified other columns and was of `feature_type` string (e.g. "Heavy rain", "Tropical cyclone") but also has some cells that are zeros (0) in the .xlsx.
- In **mixmasta**, the **MainCause** dataframe column had multiple types, but was written to a single parquet file, which does not multiple datatypes in a column, thus throwing the exception.

#### Solution

After all of the normalizer() dataframe manipulation, enforce `feature_type` in the dataframe when it is a string.

> This only works if the user accurately curates the feature_type of the submitted data; it is unclear what validation SpaceTag does on the data and `feature_type` agreement.

```
# If any qualify columns were added, the feature_type must be enforced
# here because pandas will have cast strings as ints etc.
qualify_cols = set(norm.columns).difference(set(COL_ORDER))
for col in qualify_cols:
    for feature_dict in mapper["feature"]:
        if feature_dict["name"] == col and feature_dict["feature_type"] == 'string':
            norm[col] = norm[col].astype(str)
```

### UnitTests

Four unit tests run with `admin2` are implemented:

1. Test ISO2 primary_geo; build a date day, month, year; no primary_date; feature qualifies another feature.
2. Test multi-band geotiff using asset_wealth tif with 4 bands.
3. Test qualifies columns and lag/lng primary geo
4. Test .xlsx file and a qualifies feature column with multiple dtypes (ie. rainfall error files).

**Comment by GoogleSheets** [comment]
## Update

- Added CLI and CLI `causemosify-multi` unit testing. 
- `causemosify-multi` will load and compare testing parquet files to the gold standard files in `tests/outputs`.


## Running unit tests
In the mixmasta docker container, run:
`/mixmasta/tests# /usr/bin/python3.8 -m unittest /workspaces/mixmasta/tests/test_mixmasta.py -v`

**Pull request merged**
