### PR TITLE
Feature/rtk epochtime

### PR DESCRIPTION
**Pull request by GoogleSheets**
Address Issue #9 Convert all date/time to epoch time and #16 Support various time types

If there is no `primary_time` column for `timestamp`, attempt to generate from `Time`= Month, Day or Year features.

Int values are written to the standard parquet file and will be read as FLOAT if other float/double values are present.

Djibouti Food prices data files to test (remove .txt extension):

[WFP_2021Mar31_Djibouti_FoodPricesData.csv.txt](https://github.com/jataware/mixmasta/files/6562369/WFP_2021Mar31_Djibouti_FoodPricesData.csv.txt)
[WFP_2021Mar31_Djibouti_FoodPricesData.json.txt](https://github.com/jataware/mixmasta/files/6562370/WFP_2021Mar31_Djibouti_FoodPricesData.json.txt)

### CODE REVIEW

**Comment by brandomr** [comment]
@GoogleSheets does this take into account the new approach for geo pairs (`is_geo_pair`) or "build a date" (`associated_columns`)?

**Comment by GoogleSheets** [comment]
No, I'll need to make those modifications. Regarding `is_geo_pair`, is that meant to specify geo pairs when there are more than one set of lat/log values?

**Comment by brandomr** [comment]
> Regarding `is_geo_pair`, is that meant to specify geo pairs when there are more than one set of lat/log values?

@GoogleSheets that's correct. The `coords` could be used as `primary_geo` as well, so you'll get the formatter (`lat, lon`) or (`lon, lat`) so will need to check for that.

@BecketTrotter if a "build a date" is the `primary_date` will all the associated columns for it have `primary_date` = `true`?

@GoogleSheets also worth noting that many fields are optional, meaning they won't necessarily be there. `primary_date` and `primary_geo` are examples of this; you can't expect them to be present _unless_ it is `true`. Otherwise it may or may not be a present key. I'm not sure if @BecketTrotter plans to make them always present or not.

**Comment by BecketTrotter** [comment]
- I can make all fields ever present if that would be easier for @GoogleSheets 
- All of the fields of an associated primary_date will have primary_date = True. We do input control to make sure no more than one can be marked as primary date unless they are associated.
- the value for is_geo_pair will be the geo column this column is associated with. Only long/lat can be associated with each other

**Comment by GoogleSheets** [comment]
@BecketTrotter 
> * I can make all fields ever present if that would be easier for @GoogleSheets

This shouldn't be necessary, but I'll need to make some changes to avoid dictionary key errors. 

> * All of the fields of an associated primary_date will have primary_date = True. We do input control to make sure no more than one can be marked as primary date unless they are associated.

This should makes things easier, thanks.

@brandomr 
Can you provide a use-case where there would be a second set of paired `lat/lon` values, and how would these be processed requiring the pairing? In other words, if `lat` and `lon` columns are both marked as `primary_geo` and therefore no other geo column can be `primary_geo`, then we know those are paired. If there is a second set of paired `lat/lon` not `primary_geo`, these will not be geocoded, and the columns will end up as features. Does that sound right?

**Comment by brandomr** [comment]
@GoogleSheets some of the models are logistics/migration models where each record has information about `Point A` and `Point B`. Obviously only one of the two can be `primary_geo`. So you could potentially have something like:

| origin_lat | origin_lon | dest_lat | dest_lon |
|------------|------------|----------|----------|
| 10         | 12         | 14       | 8        |
| 10         | 12         | 15       | 4        |

In this case the user would have to pick one of the pairs as `primary`

**Comment by GoogleSheets** [comment]
> @GoogleSheets some of the models are logistics/migration models where each record has information about `Point A` and `Point B`. Obviously only one of the two can be `primary_geo`. So you could potentially have something like:
> 
> origin_lat	origin_lon	dest_lat	dest_lon
> 10	12	14	8
> 10	12	15	4
> In this case the user would have to pick one of the pairs as `primary`

@brandomr This is clear. The pairs marked as `primary_geo` are processed together for geocoding. Currently, the other two fields would be treated separately as `features` and their `is_geo_pair` values ignored. 

Dates are treated similarly, where 'primary_date' will group `month`, `day`, `year` fields group together to create an epoch time (this needs to be modified in the code). If those fields are not `primary_date` then they are treated as `features`. 

So, currently, `is_geo_pair` and `date` `associated_columns` are not utilized since anything not marked as `primary` gets treated as a feature. Let me know if that should change.

**Comment by brandomr** [comment]
@GoogleSheets I think that all makes sense with the exception of `associated_columns`. I do think that if someone associates various columns and they *are not* `primary_date` we should still convert them to epoch then store them as a feature (instead of storing them as separate uncombined features).

**Comment by GoogleSheets** [comment]
> @GoogleSheets I think that all makes sense with the exception of `associated_columns`. I do think that if someone associates various columns and they _are not_ `primary_date` we should still convert them to epoch then store them as a feature (instead of storing them as separate uncombined features).

@brandomr Sounds good, I'll take care of that, and then create a bit of test data for the different combinations.

**Comment by brandomr** [comment]
Need to add `fuzzywuzzy` to requirements file

**Comment by brandomr** [comment]
I've been trying to test with this [example.csv](https://github.com/jataware/mixmasta/files/6678482/example.csv) and this [example schema](https://github.com/jataware/spacetag/blob/schema/example.json) but get this error:


```
Traceback (most recent call last):
  File "/usr/local/bin/mixmasta", line 11, in <module>
    load_entry_point('mixmasta==0.5.4', 'console_scripts', 'mixmasta')()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mixmasta-0.5.4-py3.8.egg/mixmasta/cli.py", line 25, in causemosify
    return process(input_file, mapper, geo, output_file)
  File "/usr/local/lib/python3.8/dist-packages/mixmasta-0.5.4-py3.8.egg/mixmasta/mixmasta.py", line 677, in process
    norm = normalizer(df, mapper, admin)
  File "/usr/local/lib/python3.8/dist-packages/mixmasta-0.5.4-py3.8.egg/mixmasta/mixmasta.py", line 530, in normalizer
    df = df.join(df.apply(generate_timestamp, date_mapper=assoc_columns, column_name=new_column_name, axis=1))
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 7768, in apply
    return op.get_result()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/apply.py", line 185, in get_result
    return self.apply_standard()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/apply.py", line 276, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/apply.py", line 290, in apply_series_generator
    results[i] = self.f(v)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/apply.py", line 110, in f
    return func(x, *args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/mixmasta-0.5.4-py3.8.egg/mixmasta/mixmasta.py", line 363, in generate_timestamp
    if vv["date_type"] == "day":
TypeError: 'NoneType' object is not subscriptable
```

**Comment by GoogleSheets** [comment]
@brandomr It looks like there is a typo in the [example schema](https://github.com/jataware/spacetag/blob/schema/example.json) line 78 is `associated_colums` but should be `associated_columns` (missing "n") (also looks like I should have tested with these examples).

The code isn't rigorously checking for malformed json or related; but, we could change that.

**Comment by brandomr** [comment]
Whoops! Should have validated my JSON 😅.

I think validating the mapper will happen in spacetag so that should be fine. If we validate in mixmasta we need a copy of the schema in the mixmasta repo which is not ideal since we'd have to do a git submodule or just have a copy (risky if they get out of sync!). 

I'll fix my JSON and test again.

**Pull request merged**
