### PR TITLE
multi-input causemosify 

### PR DESCRIPTION
**Pull request by GoogleSheets**
### What's new
Added a new function **`causemosify-multi`** which takes 2 arguments: 

- `--inputs` : filename of array of causemosify parameters
- `--geo` : e.g. `admin2`, `admin3`. Used for all submitted files.

and **returns a list of tuples `(dataframe, dict)`**

The `inputs` file should have following format (see below for an example):
```
[
   {
      "input_file":"file_1_*.csv",
      "mapper":"mapper_1.json",
      "output_file":"output_1"
   },
   {
      "input_file":"file_2.csv",
      "mapper":"mapper_2.json",
      "output_file":"output_2"
   }
]
```
### Rationale
Links to Issue #30
Method to causemosify multiple files at once. 

### Testing the PR
First, checkout the `feature/causemosify-multiple` branch. Then build the Docker container with:

`docker build -t mixmasta-multi .`

Then run `cd examples/causemosify-tests` and if using Windows PowerShell:

`docker run -v ${PWD}:/tmp mixmasta-multi causemosify-multi --inputs="tmp/multi-inputs.json" --geo=admin3`

`Note the wildcard * in the input_file argument. This must now be quoted so as to not break the shell.`

If successful, this will produce three parquet files: `output_1.parquet.gzip`, `output_2.parquet.gzip`, and `output_2_str.parquet.gzip`.

`multi-inputs.json` has the following structure:
```
[
   {
      "input_file":"tmp/build-a-date-qualifier_*.csv",
      "mapper":"tmp/build-a-date-qualifier.json",
      "output_file":"tmp/output_1"
   },
   {
      "input_file":"tmp/raw_excel_timestampfeature.xlsx",
      "mapper":"tmp/mixmasta_ready_annotations_timestampfeature.json",
      "output_file":"tmp/output_2"
   }
]
```
and it and its associated files are included in this PR.

### CODE REVIEW

**Comment by brandomr** [comment]
@GoogleSheets this looks great. It occurs to me that we should combine the output parquet files into 1 (or 2 if `string` feature file) since Uncharted is not expecting multiple output files per model run.

If you consider the model metadata schema, [outputs are a simple array](https://github.com/uncharted-causemos/docs/blob/master/datacubes/model.schema.json#L120-L127) of outputs, and not tied to specific output files. That's one of the major disconnects we have to solve for Uncharted--models produce **output files**, not **outputs**. Modelers think in terms of **output files** as well; but CauseMos only concerns itself with:

```
model >>> model run >>> outputs
```

Can you take a whack at extending this `causemosify_multi` function to then try to recombine the various outputs into 1 or 2 parquets? Probably you'd then not include `output_file` in the array of dictionaries sent to the function but instead just ask for that for _all_ inputs at the top as before. Let me know if that makes sense.

**Comment by GoogleSheets** [comment]
@brandomr That makes sense and the implementation is straight forward; a new optional parameter (`write_output = True`) is added to `mixmasta.process()` and the parquet writing stuff moved to `cli.causemosify_multi()`.

The only confound I see at this point is with the renamed_column_dictionaries where I simply merge them. This is used by SpaceTag to track build-a-date columns etc. and is a dictionary (`str: list`) e.g.:
```
{
	"timestamp": [
		"month_column",
		"day_column",
		"year_column"
	],
	"country_non_primary": [
		"country"
	],
	"admin1_non_primary": [
		"admin1"
	],
	"admin2_non_primary": [
		"admin2"
	],
	"admin3_non_primary": [
		"admin3"
	],
	"timestamp_non_primary": [
		"timestamp"
	]
}
```
So unless the user is careful with column names there will be overwriting and other nefarious stuff. We might want to run this by @BecketTrotter, to see what he is expecting for multiple-file implemenations.

**Comment by GoogleSheets** [comment]
### What's new (Updated)
Added a new function **causemosify-multi** which takes 3 arguments:

`--inputs`: filename of json array of causemosify parameters
`--geo` : e.g. `admin2`, `admin3`. Used for all submitted files.
`----output-file`: filename for parquets, defaults to `mixmasta_output`

and returns a tuple: `(pandas.DataFrame, dict)`

The inputs file should have following format:
```
[
   {
      "input_file":"file_1_*.csv",
      "mapper":"mapper_1.json"
   },
   {
      "input_file":"file_2.csv",
      "mapper":"mapper_2.json"
   }
]
```
for example `multi-inputs.json` :
```
[
   {
      "input_file":"tmp/build-a-date-qualifier_*.csv",
      "mapper":"tmp/build-a-date-qualifier.json"
   },
   {
      "input_file":"tmp/raw_excel_timestampfeature.xlsx",
      "mapper":"tmp/mixmasta_ready_annotations_timestampfeature.json"
   }
]
```
### Rationale
Links to Issue #30 
Method to causemosify multiple files at once.

### Testing the PR
First, checkout the feature/causemosify-multiple branch. Then build the Docker container with:

`docker build -t mixmasta-multi .`

Then run `cd examples/causemosify-tests` and if using Windows PowerShell:

`docker run -v ${PWD}:/tmp mixmasta-multi causemosify-multi --inputs="tmp/multi-inputs.json" --geo=admin3 --output-file="tmp/testing"`

`Note the wildcard * in the input_file argument. This must now be quoted so as to not break the shell.`

If successful, this will produce two parquet files: `testing.parquet.gzip` and `testing_str.parquet.gzip`.



Associated data and mapper files are included in this PR.

**Comment by brandomr** [comment]
@GoogleSheets I think that having to read `multi-inputs.json` from disk will be problematic for our Airflow setup. Is it possible to just pass that JSON in on the command line? I know it will be kind of a gross looking command, but it will save a bunch of headache. I should have caught this sooner and let you know that is what I had intended. Could be just a big quoted JSON:

```
'[{"input_file": "tmp/build-a-date-qualifier_*.csv", "mapper": "tmp/build-a-date-qualifier.json"}, {"input_file": "tmp/raw_excel_timestampfeature.xlsx", "mapper": "tmp/mixmasta_ready_annotations_timestampfeature.json"}]'
```

If that isn't possible we _can_ address it in DMC/Airflow but it will be tricky.

**Comment by GoogleSheets** [comment]
### Updated parameters
`causemosify-multi` which takes 3 arguments:

`--inputs`:  string of JSON array of causemosify parameters in quotations with delimited interior quotations
`--geo`: e.g. `admin2`, `admin3`. Used for all submitted files.
----output-file: filename for parquets, defaults to `mixmasta_output`

and returns a tuple: `(pandas.DataFrame, dict)`

### What changed
`causemosify-multi` `--inputs` now expects a JSON as a string. The interior quotation marks should be delimited:

`"[{\"input_file\": \"build-a-date-qualifier_*.csv\", \"mapper\": \"build-a-date-qualifier.json\"}, {\"input_file\": \"raw_excel_timestampfeature.xlsx\", \"mapper\": \"mixmasta_ready_annotations_timestampfeature.json\"}]"
`

**Ready to test.**

**Pull request merged**
